# Generated by Django 4.2.7 on 2023-11-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_action',
            field=models.TimeField(verbose_name='время, когда выполнять'),
        ),
    ]
